version = 3
final_space = true

[palette]
  bg = '#24273A'
  text = '#F2F2F2'
  white = '#FFFFFF'

[secondary_prompt]
  template = '# '
  foreground = 'p:blue'
  background = 'transparent'

[transient_prompt]
  template = '{{ .Shell }} # '
  foreground = 'p:pink'
  background = 'transparent'

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    style = 'plain'
    template = '{{ .UserName }}@{{ .HostName }} [{{ .Shell }}]'
    foreground = 'p:text'
    powerline_symbol = ''
    type = 'session'

  [[blocks.segments]]
    style = 'plain'
    template = ' {{ .Path }}'
    foreground = 'p:text'
    type = 'path'

    [blocks.segments.properties]
      home_icon = '~'
      style = 'agnoster_short'

  [[blocks.segments]]
    style = 'plain'
    template = ' {{ .HEAD }}'
    foreground = 'p:text'
    type = 'git'

    [blocks.segments.properties]
      branch_max-length = 25.0
      fetch_status = true

[[blocks]]
  type = 'prompt'
  alignment = 'right'
  overflow = 'hide'

  [[blocks.segments]]
    style = 'plain'
    template = ' x{{ reason .Code }}'
    foreground = 'p:green'
    type = 'status'
    alias = 'Err'
    foreground_templates = ['{{ if gt .Code 0 }}p:red{{ end }}']

  [[blocks.segments]]
    style = 'plain'
    template = ' {{ .FormattedMs }} '
    foreground = 'p:green'
    type = 'executiontime'
    foreground_templates = ['{{ if gt .Code 0 }}p:red{{ end }}']

    [blocks.segments.properties]
      always_enabled = true
      style = 'roundrock'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    style = 'plain'
    template = '#'
    foreground = 'p:green'
    type = 'text'
