frame = "none"
# TODO: Make this a template for windows
neovim-bin = "/usr/bin/env nvim"
title-hidden = true
fork = true

[font]
    normal = "FiraCode Nerd Font Mono"
    size = 10.0
    edging = "antialias"

[font.features]
    "FiraCode Nerd Font Mono Ret" = [ "+cv02", "+cv05", "+cv09", "+cv14", "+ss04", "+cv16", "+cv31", "+cv25", "+cv26", "+cv32", "+cv28", "+ss10", "+zero", "+onum"]

